---
- name: install and configure tomcat server for deployment
  hosts: nodes
  remote_user: root

  vars:
    tomcat_user: tomcat
    tomcat_path: /opt/tomcat

  tasks:
    - name: Update system package
      apt:
        upgrade: yes
        update_cache: yes
    - name: install java
      apt:
        name: openjdk-11-jdk
        state: present
    - name: check java version
      command: java --version
    - name: create user
      user:
        name: {{tomcat_user}}
    - name: Create group
      group:
        name: {{tomcat_user}}
    - name: create tomcat directory
      file:
        path: "/opt/tomcat"
        owner: {{tomcat_user}}
        group: {{tomcat_user}}
        mode: 755
        recurse: yes
    - name: Download tomcat and unarchive
      unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
      dest: {{tomcat_path}}
      remote_src: yes
      extra_opts: [--strip-components=1]
    - name: start tomcat server
      command: nohup {{tomcat_path}}/bin/start.sh
    - name: allow TCP connections
      command: sudo ufw allow 8080/tcp







